### PR TITLE
feat: new documentation

### LINKED ISSUE #22: Can't close search bar once opened
I'm using the latest version of Firefox.

When I open the search bar, it shows a dropdown of pages. This dropdown won't close again, whether I click outside it or press escape.

### PR DESCRIPTION
**Pull request by sent**
Closes #22, #19

### CODE REVIEW

**Comment by msimerson** [comment]
ready for merge?

**Comment by sent** [comment]
Hello @msimerson,

Yes, I've double checked up everything, should look cool after the build.

Thanks!

**Comment by sent** [comment]
I've synced up documentation, also in main Haraka repository settings (under social preview):

image

You'll need to upload this image https://github.com/haraka/haraka.github.com/blob/d220e192cd5377b39ba7473c0c8f5280bda3f6f5/public/preview.png

It'll make look pretty good when repository will be shared.

Thanks!

**Comment by sent** [comment]
Forgot to mention, this repository name should be changed from `haraka.github.com` to `haraka.github.io` because GitHub doesn't allow hosting any content under their subdomains anymore.

Thanks!

**Pull request merged**
