### PR TITLE
New documentation

### PR DESCRIPTION
**Pull request by sent**
Good day!

This is my personal thank you for awesome work that has been going for years.

New documentation based on [nuxt content](https://content.nuxtjs.org/), for deployment check https://nuxtjs.org/faq/github-pages/

Thank you!

### CODE REVIEW

**Review by msimerson — APPROVED** [review]

**Comment by baudehlo** [comment]
Umm, the web site is all busted now.

http://haraka.github.io/

**Comment by msimerson** [comment]
Yeah, I need to change the root, working on that. If things get too hairy, I'll just revert.

**Comment by msimerson** [comment]
While I'm figuring that out, have a look [here](http://haraka.github.io/dist/)

**Comment by msimerson** [comment]
I reverted via 'git reset' and force pushed so the site is back to normal. I was able to get the main page published properly but then the links were all busted. This will take some more looking into.

**Comment by baudehlo** [comment]
Can github pages do different sites for different branches? That'd help a
lot in trying to figure out issues. I pushed tiny fixes so many times last
time I did serious work on this.

**Comment by msimerson** [comment]
> Can github pages do different sites for different branches?

No, just one pages site per repo.

The sane way to do GH Pages (granted, I've only created [one](https://meanylodge.github.io) Pages site) was to get the Jekyll framework running locally and then do all the site creation stuff locally. When you're done and happy, check in the changes and it goes live. Thats a bit involved but its way better than the death-by-a-thousand-papercuts approach.

**Pull request merged**
